indent shell-scripts with tabs
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
Upstream-commit: 547ac1b34533f692ddc8c729ecc32416af833c8e
Component: packaging

diff --git a/components/packaging/deb/build-deb b/components/packaging/deb/build-deb
--- a/components/packaging/deb/build-deb
+++ b/components/packaging/deb/build-deb
@@ -6,7 +6,7 @@ set -e
 mkdir -p /root/build-deb/engine
 tar -C /root/build-deb -xzf /sources/engine.tgz
 mkdir -p /root/build-deb/cli
-tar  -C /root/build-deb -xzf /sources/cli.tgz
+tar -C /root/build-deb -xzf /sources/cli.tgz
 
 # link them to their canonical path
 mkdir -p /go/src/github.com/docker
@@ -16,17 +16,17 @@ ln -snf /root/build-deb/cli /go/src/github.com/docker/cli
 EPOCH="${EPOCH:-}"
 EPOCH_SEP=""
 if [[ ! -z "$EPOCH" ]]; then
-    EPOCH_SEP=":"
+	EPOCH_SEP=":"
 fi
 
 if [[ -z "$DEB_VERSION" ]]; then
-    echo "DEB_VERSION is required to build deb packages"
-    exit 1
+	echo "DEB_VERSION is required to build deb packages"
+	exit 1
 fi
 
 echo VERSION AAA $VERSION
 
-VERSION=${VERSION:-$( cat cli/VERSION )}
+VERSION=${VERSION:-$(cat cli/VERSION)}
 
 echo VERSION bbb $VERSION
 
